apiVersion: v1
kind: Service
metadata:
  name: "chuck-ui"
  namespace: "chuck"
spec:
  selector:
    app: "chuck-ui"
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: chuck-ui
  namespace: chuck
spec:
  host: chuck-ui.apps.a.okto.ocplab.io
  port:
    targetPort: http
  to:
    kind: Service
    name: chuck-ui
---
kind: DeploymentConfig
apiVersion: "v1"
metadata:
  labels:
    app: "chuck-ui"
  name: "chuck-ui"
  namespace: "chuck"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "chuck-ui"
    spec:
      containers:
      - name: "chuck-ui"
        image: " "
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: API_URL
          value: "http://chuck-api.apps.a.okto.ocplab.io"
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "chuck-ui"
        from:
          kind: "ImageStreamTag"
          name: "chuck-ui:latest"
          namespace: "chuck"

