kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "chuck-ui"
  namespace: chuck-ops
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/Dimss/chuck-ui"
  strategy:
    customStrategy:
      from:
        kind: "ImageStreamTag"
        name: "base-builder:stable"
      secrets:
      - secretSource:
          name: "builder-config"
        mountPath: "/tmp/builder-config"
      env:
        - name: "OPS_TYPE"
          value: "build"
  triggers:
  - github:
      secret: dGvu1slX2WybtV_HOcYJ
    type: "GitHub"





