kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "custom"
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/Dimss/chuck-ui"
  strategy:
    customStrategy:
      from:
        kind: "DockerImage"
        name: "dimssss/custom-builder:0.11"
      secrets:
      - secretSource:
          name: "builder-config"
        mountPath: "/tmp/builder-config"
  triggers:
  - github:
      secret: dGvu1slX2WybtV_HOcYJ
    type: "GitHub"
#  - generic:
#      secret: dGvu1slX2WybtV_HOcYJ
#    type: Generic
#    allowEnv: true





