kind: ImageStream
apiVersion: v1
metadata:
  namespace: "chuck"
  name: "chuck-ui"
spec:
  tags:
  - from:
      kind: DockerImage
      name: "docker-registry.default.svc:5000/chuck/ui"
    name: "latest"